name: Generate AWS Infrastructure Diagram

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  generate-diagram:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Python dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y graphviz
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r diagram_generator/requirements.txt

      - name: Generate diagram
        run: |
          python diagram_generator/generate_diagram.py

      - name: Commit and push diagram
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add terraform_aws_demo_diagram.png
          git commit -m "Auto-update AWS infrastructure diagram" || echo "No changes to commit"
          git push
